### ISSUE TITLE
I want to add ocular compartment in my PBPK model

### ISSUE THREAD

**Issue by ImSuajo** [Open-Systems-Pharmacology/Suite#116]
Hello.
I tried to predict ocular concentration using PK-SIM.
But there is not ocular compartment in PK-SIM.
Can you add ocular compartment in PK-SIM? or if I have to add ocular compartment by myself, how can I do this?

Answer me plz....

**Comment by Yuri05** [comment]
Please ask questions in the [forum](https://github.com/Open-Systems-Pharmacology/Forum/discussions)

**Comment by maalbrec89** [comment]
@ImSuajo contact esqLABS GmbH, we can help you. 
info@esqlabs.com
