### ISSUE TITLE
Database query

### ISSUE THREAD

**Issue by SoniaK007** [Open-Systems-Pharmacology/Suite#118]
Hy, I am new to PkSim but not to pharmacometrics. I'm trying to run a simulation with PkSim from a literature example (Kuepfer et al). I need to download the "enzyme expression database". I tried to find it on the website but I could not. Can you send me a link to download the database? I am working with version 11.  
When I select CYP1A2 in "Individual->Metabolization", all values for the organ are 0%. 
Thanks for your help.

**Comment by PavelBal** [comment]
The data base can be downloaded [here](https://github.com/Open-Systems-Pharmacology/Gene-Expression-Databases/releases/download/v2.0.0/GENEDB_human.expressionDb).

Also check out the documentation how to add an expression from the data base:

https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-expression-profile#the-workflow

**Comment by SoniaK007** [comment]
TY !
