### ISSUE TITLE
Create an msi package for the releases

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/Suite#148]
So the suite can be installed via intunes.

**Comment by PavelBal** [comment]
@Yuri05 @rwmcintosh @msevestre I cannot assign it to any project..

**Comment by rwmcintosh** [comment]
added to v12

**Comment by Yuri05** [comment]
@PavelBal IS an MSI really required? Or would e.g. `OSPSuite-Full.12.0.307.exe /install /quiet` do the job?

**Comment by PavelBal** [comment]
@SteDev78 could you comment?

**Comment by rwmcintosh** [comment]
What's the plan here.

We have several items that get installed using the 'Suite' installer. That installer bundles a few prerequisites as well as MSI installers of MoBi and PK-Sim.

So if the plan is just to run PK-Sim and MoBi installers, then we already have those as MSI. Is that enough?

**Comment by rwmcintosh** [comment]
Or use this to create a compatible intunewin file from the exe installer.?

https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool

**Comment by PavelBal** [comment]
I think it should be sufficient to install the apps separately.
