### ISSUE TITLE
Unable to open modules in MoBi

### ISSUE THREAD

**Issue by duoduo982** [Open-Systems-Pharmacology/Suite#149]
https://github.com/user-attachments/assets/b4f0b98e-b3a4-4c1f-b55d-7a1af51aba04

**Comment by rwmcintosh** [comment]
What was it that you clicked when the views all disappeared I could not quite see it.

**Comment by duoduo982** [comment]
Unable to display module，I clicked on the module under view

---- Replied Message ----
| From | Robert ***@***.***> |
| Date | 12/05/2024 21:07 |
| To | Open-Systems-Pharmacology/Suite ***@***.***> |
| Cc | duoduo982 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Open-Systems-Pharmacology/Suite] Unable to open modules in MoBi (Issue #149) |

What was it that you clicked when the views all disappeared I could not quite see it.

**Comment by duoduo982** [comment]
Yesterday it was working fine, this morning I opened it and couldn't find the module

---- Replied Message ----
| From | Robert ***@***.***> |
| Date | 12/05/2024 21:07 |
| To | Open-Systems-Pharmacology/Suite ***@***.***> |
| Cc | duoduo982 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Open-Systems-Pharmacology/Suite] Unable to open modules in MoBi (Issue #149) |

What was it that you clicked when the views all disappeared I could not quite see it.

**Comment by rwmcintosh** [comment]
Ok to fix it you close all the mobi instances and then browse to the folder

C:\Users\<user>\AppData\Roaming\Open Systems Pharmacology\MoBi

You will find version folders there. You should remove the version folder you are working with.

**Comment by rwmcintosh** [comment]
Ok to fix it you close all the mobi instances and then browse to the folder

C:\Users\<user>\AppData\Roaming\Open Systems Pharmacology\MoBi

You will find version folders there. You should remove the version folder you are working with.

**Comment by duoduo982** [comment]
OK，I will try,thank you very much

---- Replied Message ----
| From | Robert ***@***.***> |
| Date | 12/05/2024 21:15 |
| To | Open-Systems-Pharmacology/Suite ***@***.***> |
| Cc | duoduo982 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Open-Systems-Pharmacology/Suite] Unable to open modules in MoBi (Issue #149) |

Ok to fix it you close all the mobi instances and then browse to the folder

C:\Users<user>\AppData\Roaming\Open Systems Pharmacology\MoBi

You will find version folders there. You should remove the version folder you are working with.

**Comment by rwmcintosh** [comment]
If you could do me a favour, zip the folder before you delete it and attach it here?

**Comment by duoduo982** [comment]
Hello, I'm sorry to ask, but is this the right folder?













At 2024-12-05 21:19:24, "Robert McIntosh" ***@***.***> wrote:

If you could do me a favour, zip the folder before you delete it and attach it here?

**Comment by rwmcintosh** [comment]
> Hello, I'm sorry to ask, but is this the right folder? At 2024-12-05 21:19:24, "Robert McIntosh" ***@***.***> wrote: If you could do me a favour, zip the folder before you delete it and attach it here? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Sorry I don't see an image in the issue. Maybe the email removed the attachment?

**Comment by rwmcintosh** [comment]
> Hello, I'm sorry to ask, but is this the right folder? At 2024-12-05 21:19:24, "Robert McIntosh" ***@***.***> wrote: If you could do me a favour, zip the folder before you delete it and attach it here? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

I don't see an image. Was an attachment removed by the email somehow?

**Comment by duoduo982** [comment]
Which one should I delete?

---- Replied Message ----
| From | Robert ***@***.***> |
| Date | 12/05/2024 21:19 |
| To | Open-Systems-Pharmacology/Suite ***@***.***> |
| Cc | duoduo982 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Open-Systems-Pharmacology/Suite] Unable to open modules in MoBi (Issue #149) |

If you could do me a favour, zip the folder before you delete it and attach it here?

**Comment by rwmcintosh** [comment]
I can't see any images attached so I'm not sure what you're referring to.

If you are using MoBi V12, you should remove the 12.0 folder as is shown in my screenshot

![image](https://github.com/user-attachments/assets/9d292ccc-0d4b-4c95-875e-8133d82c2d0e)

**Comment by duoduo982** [comment]
Which one should I delete?

---- Replied Message ----
| From | Robert ***@***.***> |
| Date | 12/05/2024 22:19 |
| To | Open-Systems-Pharmacology/Suite ***@***.***> |
| Cc | duoduo982 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Open-Systems-Pharmacology/Suite] Unable to open modules in MoBi (Issue #149) |

Hello, I'm sorry to ask, but is this the right folder? At 2024-12-05 21:19:24, "Robert McIntosh" @.> wrote: If you could do me a favour, zip the folder before you delete it and attach it here? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

I don't see an image. Was an attachment removed by the email somehow?

**Comment by duoduo982** [comment]
My version is 11.3, should I delete the 11.3 folder?

---- Replied Message ----
| From | Robert ***@***.***> |
| Date | 12/05/2024 22:21 |
| To | Open-Systems-Pharmacology/Suite ***@***.***> |
| Cc | duoduo982 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Open-Systems-Pharmacology/Suite] Unable to open modules in MoBi (Issue #149) |

I can't see any images attached so I'm not sure what you're referring to.

If you are using MoBi V12, you should remove the 12.0 folder as is shown in my screenshot

image.png (view on web)

**Comment by rwmcintosh** [comment]
yes, but if you can, zip it and attach here so I can troubleshoot this problem for future.

**Comment by duoduo982** [comment]
Which one should I delete?

---- Replied Message ----
| From | Robert ***@***.***> |
| Date | 12/05/2024 22:21 |
| To | Open-Systems-Pharmacology/Suite ***@***.***> |
| Cc | duoduo982 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Open-Systems-Pharmacology/Suite] Unable to open modules in MoBi (Issue #149) |

I can't see any images attached so I'm not sure what you're referring to.

If you are using MoBi V12, you should remove the 12.0 folder as is shown in my screenshot

image.png (view on web)

**Comment by duoduo982** [comment]
I have fixed it, the attachment has been emailed to you, thank you very much and have a nice life!

---- Replied Message ----
| From | Robert ***@***.***> |
| Date | 12/05/2024 22:26 |
| To | Open-Systems-Pharmacology/Suite ***@***.***> |
| Cc | duoduo982 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Open-Systems-Pharmacology/Suite] Unable to open modules in MoBi (Issue #149) |

yes, but if you can, zip it and attach here so I can troubleshoot this problem for future.

**Comment by rwmcintosh** [comment]
thanks
