### ISSUE TITLE
Unable to install version 7.2

### ISSUE THREAD

**Issue by IngridMichon** [Open-Systems-Pharmacology/Suite#31]
I was unable to unstall the full version 7.2 after having installed version 7.4 before. It says that a newer version was already installed. This was not the case, I removed it using uninstall. I also removed the user app data for OPS.
When using the portable version of 7.2, it opens up but does not work when trying to open a project file eg.
Any suggestions for me to use version 7.2 in some way?

thanks

**Comment by msevestre** [comment]
@all: I moved this issue to the Suite installation issue tracker so that we do not spam everyone watching the Forum

**Comment by Yuri05** [comment]
>Sorry, still same error for both files.

Ok please try the next one:
[OSPSuite.Serializer_04.zip](https://github.com/Open-Systems-Pharmacology/Suite/files/2876521/OSPSuite.Serializer_04.zip)

If it still doesn't help (and to be honest, I don't think it will), please try the following steps:
* Extract _S1.pkml_ from attached [S1.zip](https://github.com/Open-Systems-Pharmacology/Suite/files/2876535/S1.zip)
* Start **MoBi**, select **File**:arrow_right:**New**:arrow_right:**Amount Based Reactions**
* Select **File**:arrow_right:**Open Simulation** and select extracted file _S1.pkml_
Did it work? If not: same error message or smthg different?

If this worked, Select **File**:arrow_right:**Open Simulation** again and now select an example simulation installed with the OSP setup (e.g. **C:\ProgramData\Open Systems Pharmacology\MoBi\7.4\Examples\4-Hydroxy-Diclofenac.pkml**)
Did it work? If not: same error message or smthg different?

If this also worked, try the following steps **in PK-Sim**. As soon as you cannot reopen saved project: zip it and attach along with the error message; no need to perform further test steps.
1. Create an empty project; save the project and reopen
2. Create arbitrary individual; save the project and reopen
3. Create arbitrary population; save the project and reopen
4. Create arbitrary compound; save the project and reopen
5. Create arbitrary formulation; save the project and reopen
6. Create arbitrary administration protocol; save the project and reopen
7. Create arbitrary simulation using building blocks created before; save the project and reopen

**Comment by msevestre** [comment]
@IngridMichon If you use the portable version of 7.4 (the latest release), can you open and save pksim model?

**Comment by IngridMichon** [comment]
Yes,  I can! The portable 7.3 version works fine as well

**Comment by IngridMichon** [comment]
> Ok please try the next one:
> [OSPSuite.Serializer_04.zip](https://github.com/Open-Systems-Pharmacology/Suite/files/2876521/OSPSuite.Serializer_04.zip)
> 
No, does not work

> If it still doesn't help (and to be honest, I don't think it will), please try the following steps:
> 
> * Extract _S1.pkml_ from attached [S1.zip](https://github.com/Open-Systems-Pharmacology/Suite/files/2876535/S1.zip)
> * Start **MoBi**, select **File**➡️**New**➡️**Amount Based Reactions**
> * Select **File**➡️**Open Simulation** and select extracted file _S1.pkml_
>   Did it work? If not: same error message or smthg different?

Worked just fine

>> If this worked, Select **File**➡️**Open Simulation** again and now select an example simulation installed with the OSP setup (e.g. **C:\ProgramData\Open Systems Pharmacology\MoBi\7.4\Examples\4-Hydroxy-Diclofenac.pkml**)
> Did it work? If not: same error message or smthg different?

Yes, worked fine and could run the model
> 
> If this also worked, try the following steps **in PK-Sim**. As soon as you cannot reopen saved project: zip it and attach along with the error message; no need to perform further test steps.
> 
> 1. Create an empty project; save the project and reopen
> 2. Create arbitrary individual; save the project and reopen
> 3. Create arbitrary population; save the project and reopen
> 4. Create arbitrary compound; save the project and reopen
> 5. Create arbitrary formulation; save the project and reopen
> 6. Create arbitrary administration protocol; save the project and reopen
> 7. Create arbitrary simulation using building blocks created before; save the project and reopen

But then this  failed already at step 1 (using the PKsim.exe from the temp folder)

**Comment by IngridMichon** [comment]
[PKsim_test.zip](https://github.com/Open-Systems-Pharmacology/Suite/files/2879129/PKsim_test.zip)

**Comment by Yuri05** [comment]
@IngridMichon Ok, without taking a closer look at your PC I don't see any further chance to figure out what goes wrong. I would suggest to either use a newer version (7.3 or 7.4). Or to try to install 7.2 on a different computer.
