### ISSUE TITLE
Pk-sim : the database of metabolizing enzyme is not available? 

### ISSUE THREAD

**Issue by Tom-eng-ux** [Open-Systems-Pharmacology/Suite#61]
[新建 Microsoft Word 文档.docx](https://github.com/Open-Systems-Pharmacology/Suite/files/4689279/Microsoft.Word.docx)
I downloaded the 'Gene expression database (human)' ,

**Comment by StephanSchaller** [comment]
You then have to "load" it in PK.Sim. (check the manual / documentation and search for expression database)

**Comment by Tom-eng-ux** [comment]
thanks for your reply! i tried to 'load" it in PK-sim, but i can't find the  to check the manual / documentation and search for expression database. And my pK-sim is vesion 8.0.

**Comment by Tom-eng-ux** [comment]
thanks for your help! i have solved this problem with your help. thank you!
