### ISSUE TITLE
use `{pkgdown}` GHA to build a static website for R packages

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/Suite#90]
For any other package, this would be rather [straightforward](https://github.com/r-lib/actions/blob/master/.github/workflows/pkgdown.yaml), but given the system requirements our packages have, it will require a bit more work.

If someone else doesn't manage to get to it sooner, I will work on this.

**Comment by msevestre** [comment]
@IndrajeetPatil What's in the website? Can you show me an example?

**Comment by IndrajeetPatil** [comment]
Sure, here is an example:
https://indrajeetpatil.github.io/statsExpressions/

**Comment by msevestre** [comment]
Very nice. Is this created based on vignettes?

**Comment by IndrajeetPatil** [comment]
The whole shebang! It creates `Reference` section from `.Rd` files, `Articles` from vignettes, `index` page from `README`, etc.

I have created PRs to OSP R package repos that sets up static websites. 

In the future, we should automate this process using GHA.

**Comment by IndrajeetPatil** [comment]
Closing in favor of #94.
