### ISSUE TITLE
use github actions for R packages

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/Suite#94]
I can try to take a stab at this:

- for running `R CMD Check` on both Windows and Linux for different R versions
- for computing code coverage
- for detecting lints 
- for building a static website

And then we can stop relying on AppVeyor, if we want.

Progress

- [ ] tlf
- [ ] ospsuite
- [x] ospsuite.utils
- [ ] ospsuite.reportingengine

**Comment by IndrajeetPatil** [comment]
Templates to adapt from here:
https://github.com/r-lib/actions/tree/master/.github/workflows

**Comment by Yuri05** [comment]
For the Reporting Engine (RE) I've created a [docker based Github Action for testing](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/develop/.github/workflows/LinuxImages.yml) under some Linux derivates.
However it does not install the RE package but runs RE-tests directly from the source code.

This was just a **temporary** solution. Having a proper actions which creates/takes the package and execute not only the unit tests but also all you have proposed above would be beneficial for sure.

This RE Github Action uses docker images for the ospsuite R package which are created in https://github.com/Open-Systems-Pharmacology/Docker-Images-Ospsuite-R on demand. Those docker images are based on the docker images created in https://github.com/Open-Systems-Pharmacology/Docker-Base-Images on demand. Latter contain all non-OSP prerequisites (like MONO, .NET, etc.). Those docker images are released in the OSP package repository (https://github.com/orgs/Open-Systems-Pharmacology/packages). When we have "proper" GitHub-Actions, those "Docker-Images" repos can be dropped in favor of the new actions.
